### ISSUE TITLE
Moving any component with link into a loop makes it disappear

### ISSUE THREAD

**Issue by mozfet** [mozfet/ExpertBox#103]
Moving a branch with linked expression from or into a loop loses  its content in the designer.
Moving an expression with a link into a loop or serie causes the expression to disappear.

![2018-02-22_17-42-00](https://user-images.githubusercontent.com/5113240/36547940-b2238998-17f7-11e8-9f2c-bd572d29c6b8.png)

![2018-02-22_17-42-00 1](https://user-images.githubusercontent.com/5113240/36547945-b448e4fc-17f7-11e8-8629-2e549c7bb6e2.png)

**Comment by mozfet** [comment]
```
jQuery.fn.init(4) [div#tebCdComponentfjnRKeAMjZ5qDDnno.dragulaCol.tebCdSerie.dragulaContainer, div#tebCdComponentysq9r2At9azA6AyaQ.dragulaCol.tebCdPage.dragulaContainer, div#tebCdComponentPBfs4cFhsFDjJ5eBX.dragulaCol.tebCdText, div#tebCdComponentwd6sCp2BsNndhbFt9.dragulaCol.tebCdExpression, prevObject: jQuery.fn.init(1)]
log.js:394 debug link                         : onCreate.autorun.target: expression3
log.js:394 debug link                         : onCreate.autorun.components: (5) [{…}, {…}, {…}, {…}, {…}]
log.js:394 debug link                         : AnchorId: PBfs4cFhsFDjJ5eBX
log.js:394 debug link                         : Anchor name  welcomeText
log.js:394 debug link                         : AutoLink.findRoute: anchorIsDecendantOfSibling
serie.js:29 tebCdSerie.onRendered.autorun: new components: []
log.js:394 debug link                         : onCreate.autorun.target: expression3
log.js:394 debug link                         : onCreate.autorun.components: (5) [{…}, {…}, {…}, {…}, {…}]
log.js:394 debug link                         : AnchorId: PBfs4cFhsFDjJ5eBX
log.js:394 debug link                         : Anchor name  welcomeText
log.js:394 debug link                         : AutoLink.findRoute: anchorIsDecendantOfSibling
construct.js:109 construct.dragula.onDrop.component.elementComponent: {_id: "wd6sCp2BsNndhbFt9", name: "expression3", parentId: "fjnRKeAMjZ5qDDnno", constructId: "F4kb2XZvFb5vGfbuG", type: "expression", …}
construct.js:121 construct.dragula.onDrop.component.siblingComponent: undefined
construct.js:155 construct.dragula.onDrop.priority: 1
construct.js:169 construct.dragula.onDrop.componentsForRerouting: [{…}]
log.js:394 warning link                       : Link.find: Invalid perspective or specification.
construct.js:190 construct.dragula.onDrop.anchorIds: {wd6sCp2BsNndhbFt9: Array(1)}
log.js:394 debug link                         : onCreate.autorun.target: expression3
log.js:394 debug link                         : onCreate.autorun.components: (5) [{…}, {…}, {…}, {…}, {…}]
log.js:394 debug link                         : AnchorId is not defined, find it by following link.
log.js:394 debug link                         : Link.find.spec: -welcomePage>welcomeText
log.js:394 debug link                         : links.fetch.newPerspective: expression3
log.js:394 debug link                         : link.recursiveFindLink.perspectiveId: wd6sCp2BsNndhbFt9
log.js:394 debug link                         : link.recursiveFindLink.perspective.name: expression3
log.js:394 debug link                         : link.recursiveFindLink.jump: -
log.js:394 debug link                         : link.recursiveFindLink: there is more spec
log.js:394 debug link                         : link.recursiveFindLink.name welcomePage
log.js:394 debug link                         : link.recursiveFindLink.jump: sibling
log.js:394 debug link                         : link.fetchLinkParent.perspective.name: expression3
log.js:394 debug link                         : link.fetchLinkParent.perspective.subType: undefined
log.js:394 debug link                         : link.fetchLinkParent.parent.name: serie2
log.js:394 debug link                         : link.fetchLinkParent.parent: serie2
log.js:394 debug link                         : link.recursiveFindLink.jump.sibling: specified target
log.js:394 debug link                         : link.recursiveFindLink.jump.sibling.perspective: expression3
log.js:394 debug link                         : link.fetchLinkParent.perspective.name: expression3
log.js:394 debug link                         : link.fetchLinkParent.perspective.subType: undefined
log.js:394 debug link                         : link.fetchLinkParent.parent.name: serie2
log.js:394 debug link                         : link.fetchLinkParent.parent: serie2
log.js:394 debug link                         : link.recursiveFindLink.jump.sibling.perspective.parent: serie2
log.js:394 debug link                         : link.recursiveFindLink.jump.sibling: no child by name
log.js:394 debug link                         : links.fetch.result: undefined
log.js:394 debug link                         : AnchorId: undefined
meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:992 Exception in queued task: Error:  [Component.findComponents: invalid input]
    at Object.log (http://localhost:3000/packages/mozfet_meteor-logs.js?hash=1e3dcdedf327decb0c8ecb963ca2a93fb18d958d:716:11)
    at Object.findComponent [as find] (/imports/api/component/component.js:68:9)
    at Blaze.View.eval (/imports/ui/components/designer/link/link.js:70:28)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1931:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:229:10)
construct.js:197 construct.dragula.onDrop.reroutingLinks.targetId: wd6sCp2BsNndhbFt9
construct.js:202 construct.dragula.onDrop.reroutingLinks.anchorId: undefined
meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:992 Exception in delivering result of invoking 'moveComponent': Error:  [undefined inputs]
    at Object.log (http://localhost:3000/packages/mozfet_meteor-logs.js?hash=1e3dcdedf327decb0c8ecb963ca2a93fb18d958d:716:11)
    at findRoute (/imports/api/links/autolink.js:31:9)
    at Object.findSafeRoute (/imports/api/links/autolink.js:171:15)
    at eval (/imports/ui/components/designer/construct/construct.js:273:31)
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:1167:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:3682:12)
    at MethodInvoker.dataVisible (http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:3712:10)
    at http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:4571:7
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:11)
```

**Comment by mozfet** [comment]
![2018-03-03_13-14-07](https://user-images.githubusercontent.com/5113240/36933648-95359a16-1ee5-11e8-8a42-276836928c91.png)

**Comment by mozfet** [comment]
Fixed the problem by not relying on the anchorId in the DOM, but rather tracking in with the link in the database. If the link cannot be found, try to find it using the anchorId; alternatively if the the anchorId exists, reroute the link. This seems to take care of all moving and renaming issues.
