### ISSUE TITLE
Payment  Connection Error

### ISSUE THREAD

**Issue by mozfet** [mozfet/ExpertBox#149]
Environment: PROD
Reproduce: Try to buy credits
Expected: Payments should work
Percieved: Client error toast "connection error" is shown.
Percieved: Server log ```could not generate braintree client token```, ```Authentication Error```

```
2018-05-04 12:57:53+02:00info payments : created payment { _id: 'QeQk3Rjk2iJx3Yg2Q',
2018-05-04 12:57:53+02:00 type: 'BRAINTREE',
2018-05-04 12:57:53+02:00 amount: '1.00',
2018-05-04 12:57:53+02:00 currency: 'EUR',
2018-05-04 12:57:53+02:00 credits: 1,
2018-05-04 12:57:53+02:00 ownerId: 'ZpBc6oCus5MJ2Fzk5',
2018-05-04 12:57:53+02:00 state: 'CREATED',
2018-05-04 12:57:53+02:00 updatedAt: 2018-05-04T10:57:53.458Z,
2018-05-04 12:57:53+02:00 createdAt: 2018-05-04T10:57:53.458Z,
2018-05-04 12:57:53+02:00 creditValidityDays: 365 }
2018-05-04 12:57:54+02:00warning braintree : could not generate braintree client token [ { authenticationError: Authentication Error
2018-05-04 12:57:54+02:00 at Object.AuthenticationError (/app/bundle/programs/server/npm/node_modules/braintree/lib/braintree/exceptions.js:7:15)
2018-05-04 12:57:54+02:00 at Http.checkHttpStatus (/app/bundle/programs/server/npm/node_modules/braintree/lib/braintree/http.js:26:37)
2018-05-04 12:57:54+02:00 at Http.<anonymous> (/app/bundle/programs/server/npm/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
2018-05-04 12:57:54+02:00 at IncomingMessage.response.on (/app/bundle/programs/server/npm/node_modules/braintree/lib/braintree/http.js:91:28)
2018-05-04 12:57:54+02:00 at emitNone (events.js:111:20)
2018-05-04 12:57:54+02:00 at IncomingMessage.emit (events.js:208:7)
2018-05-04 12:57:54+02:00 at endReadableNT (_stream_readable.js:1064:12)
2018-05-04 12:57:54+02:00 at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-05-04 12:57:54+02:00 at process._tickDomainCallback (internal/process/next_tick.js:218:9) name: 'authenticationError', type: 'authenticationError' } ]
```

**Comment by mozfet** [comment]
We have switched over to live payments, updated the payment credentials on the server using the BrainTree PROD API keys... it worked fine with the Sandbox!

**Comment by mozfet** [comment]
Found the problem, the environment was hardcoded to the sandbox. I made it configurable with Meteor settings per environment.

**Comment by mozfet** [comment]
Payment Connection Error disappeared with the environment change. There is a new server warning ```Customer specified by customer_id does not exist``` together with a client side toast.

**Comment by mozfet** [comment]
The 'braintree.generateClientToken' server method call the Braintree.generateClientToken server API funtion (/imports/payments/braintree/server/api) with arguments. 

The user document is retrieved from the User MongoDB collection, and checked if it has a payment object, which is used to . Since we used the sandbox before, many users already have user.payments.braintree.customerId set, but that is for a sandbox account...

Thus, as part of migration from sandbox to live, all user payment objects must be removed from the database.

**Comment by mozfet** [comment]
Added an admin function to remove all user payment objects, tested it on DEV and it works (forgot all previously used payment credentials). There is now a button in the admin control panel to do this.
