### ISSUE TITLE
Construct design changes lost

### ISSUE THREAD

**Issue by mozfet** [mozfet/ExpertBox#32]
For some reason my updates to a private construct I'm building not being stored.

**Comment by mozfet** [comment]
It seems the is a pattern that whatever is created the first time the construct is designed stays. Any subsequent changes are dropped.

**Comment by mozfet** [comment]
This may have something to do with admin rights required to update examples. However this is not an example, but access rules share a query.

**Comment by mozfet** [comment]
Found the culprit in the server log...
```
Exception while invoking method 'moveComponent' ReferenceError: Log is not defined
gm8qm
2017-10-06 15:37:05+02:00 at [object Object].moveComponent (imports/api/session/component.js:742:2)
gm8qm
2017-10-06 15:37:05+02:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
gm8qm
2017-10-06 15:37:05+02:00 at packages/ddp-server/livedata_server.js:719:19
gm8qm
2017-10-06 15:37:05+02:00 at [object Object].EVp.withValue (packages/meteor.js:1135:15)
gm8qm
2017-10-06 15:37:05+02:00 at packages/ddp-server/livedata_server.js:717:46
gm8qm
2017-10-06 15:37:05+02:00 at [object Object].EVp.withValue (packages/meteor.js:1135:15)
gm8qm
2017-10-06 15:37:05+02:00 at packages/ddp-server/livedata_server.js:715:46
gm8qm
2017-10-06 15:37:05+02:00 at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
gm8qm
2017-10-06 15:37:05+02:00 at packages/ddp-server/livedata_server.js:559:43
```

**Comment by mozfet** [comment]
An exception is thrown on server because the Log component was not imported into this module. Sometimes I miss compiler errors.

**Comment by mozfet** [comment]
fixed
